package io.github.jvondoellinger.rising_helpdesk.profile.application.handlers.commands;

import io.github.jvondoellinger.rising_helpdesk.profile.application.commands.AddPermissionsAccessProfileCommand;
import io.github.jvondoellinger.rising_helpdesk.profile.application.commands.RemovePermissionsAccessProfileCommand;
import io.github.jvondoellinger.rising_helpdesk.sharedkernel.application.CommandHandler;

public interface AddPermissionsAccessProfileHandler extends CommandHandler<AddPermissionsAccessProfileCommand> {
}
