package io.github.jvondoellinger.rising_helpdesk.access_control.profiles.application.handlers.commands.accessprofile;

import io.github.jvondoellinger.rising_helpdesk.access_control.profiles.application.commands.accessprofile.AddPermissionsAccessProfileCommand;
import io.github.jvondoellinger.rising_helpdesk.sharedkernel.application.CommandHandler;

public interface AddPermissionsAccessProfileHandler extends CommandHandler<AddPermissionsAccessProfileCommand> {
}
