server.port=9090

spring.application.name=gateway
# Ticket routes
spring.cloud.gateway.server.webflux.routes[0].id=ticket_v1_module
spring.cloud.gateway.server.webflux.routes[0].uri=http://127.0.0.1:8001
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/ticket,
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[0].filters[1]=PrefixPath=/api/ticket

management.endpoints.web.exposure.include=*

logging.level.org.springframework.cloud.gateway=TRACE