package com.github.jvondoellinger.agp_protocol.application.accessProfile.useCases;

import com.github.jvondoellinger.agp_protocol.application.accessProfile.dtos.createAccessProfile.CreateAccessProfileRequestDTO;
import com.github.jvondoellinger.agp_protocol.application.accessProfile.dtos.createAccessProfile.CreateAccessProfileResponseDTO;
import com.github.jvondoellinger.agp_protocol.application.shared.CommandUseCase;

public interface CreateAccessProfileCommandUseCase extends CommandUseCase<CreateAccessProfileRequestDTO, CreateAccessProfileResponseDTO> {
}
