package com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.useCases;

import com.github.jvondoellinger.agp_protocol.shared_kernel.application_commons.CommandUseCase;
import com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.commands.CreateAccessProfileCommand;
import com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.queries.AccessProfileDetails;

public interface CreateAccessProfileCommandUseCase extends CommandUseCase<CreateAccessProfileCommand, AccessProfileDetails> {
}
