package com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.useCases;

import com.github.jvondoellinger.agp_protocol.shared_kernel.application_commons.CommandUseCase;
import com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.commands.DeleteAccessProfileCommand;
import com.github.jvondoellinger.agp_protocol.api_authorization.userProfile_module.application.queries.AccessProfileDetails;

public interface DeleteAccessProfileCommandUseCase extends CommandUseCase<DeleteAccessProfileCommand, AccessProfileDetails> {

}
