package io.github.jvondoellinger.rising_helpdesk.profile.application.handlers.commands;

import io.github.jvondoellinger.rising_helpdesk.profile.application.commands.ChangePermissionsAccessProfileCommand;
import io.github.jvondoellinger.rising_helpdesk.sharedkernel.application.CommandHandler;

public interface ChangePermissionsAccessProfileCommandHandler extends CommandHandler<ChangePermissionsAccessProfileCommand> {
}
