STOP REPLICA;

RESET REPLICA ALL;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST = 'mysql-master',
  SOURCE_PORT = 3306,
  SOURCE_USER = 'repl_user',
  SOURCE_PASSWORD = 'secret123',
  SOURCE_LOG_FILE = 'mysql-bin.000003',
  SOURCE_LOG_POS = 1046,
  GET_SOURCE_PUBLIC_KEY = 1;

START REPLICA;