FROM proxysql/proxysql:2.5.5

# Copia o arquivo de configuração
COPY proxysql.cnf /etc/proxysql.cnf

# Porta admin (6032) e MySQL (6033)
EXPOSE 6032 6033

# Comando padrão
CMD ["proxysql", "-f", "-c", "/etc/proxysql.cnf"]
