-- USUARIO DO PROXYSQL 
CREATE USER 'proxysql_user'@'%' IDENTIFIED BY "secret123";

GRANT ALL PRIVILEGES ON *.* TO 'proxysql_user'@'%';
FLUSH PRIVILEGES;

-- USUARIOS DE REPLICA 
CREATE USER IF NOT EXISTS 'repl_user'@'%' IDENTIFIED BY 'secret123';

GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl_user'@'%';
FLUSH PRIVILEGES;

FLUSH PRIVILEGES;


-- INICIANDO REPLICAS 
STOP REPLICA;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST = 'mysql_master',
  SOURCE_PORT = 3306,
  SOURCE_USER = 'repl_user',
  SOURCE_PASSWORD = 'secret123',
  SOURCE_LOG_FILE = 'mysql-bin.000003',
  SOURCE_LOG_POS = 4,
  GET_SOURCE_PUBLIC_KEY = 1;

START REPLICA;
SHOW REPLICA STATUS\G