-- USUARIO DO PROXYSQL
CREATE USER 'proxysql_user'@'%' IDENTIFIED BY "secret123";

GRANT ALL PRIVILEGES ON *.* TO 'proxysql_user'@'%';
FLUSH PRIVILEGES;

-- USUARIO DE REPLICACAO
CREATE USER IF NOT EXISTS 'repl_user'@'%' IDENTIFIED BY 'secret123';

GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl_user'@'%';
FLUSH PRIVILEGES;